name: Push to Lokalise  
on:  
  workflow_dispatch:

jobs:  
  build:  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push files to Lokalise
        uses: lokalise/lokalise-push-action@v3.8.1
        with:
          api_token: ${{ secrets.LOKALISE_API_TOKEN }}
          project_id: ${{ secrets.LOKALISE_PROJECT_ID }}
          base_lang: en
          translations_path: |
            locale
          file_format: json
          file_ext: json
          use_tag_tracking: true
          skip_default_flags: true
          rambo_mode: true
          additional_params: |
          --convert-placeholders: true
          --replace-modified: true
          
